### ISSUE TITLE
Update SetValidatorMaxCount to appropriate value

### ISSUE THREAD

**Issue by chgorman** [MadBase/MadNet#40]
The maximum number of validators need to be updated to correctly reflect current limitations. Some of these limitations come from Validators staking cost, communication limitations, and ability to successfully submit accusations within the current gas limit.

These limitations can be determined from testing.

**Comment by Cr0wn-Gh0ul** [comment]
https://github.com/MadBase/MadNet/blob/main/blockchain/contracts.go#L571
